// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igvwurlyqsdvnrvvtbbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlndnd1cmx5cXNkdm5ydnZ0YmJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODU4MTUsImV4cCI6MjA3MDA2MTgxNX0.dkkdXuC2t-n8yh3ARAmdAbahHk_EtmqWL6bGt-1qn-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});